name: Deploy to Cloudflare Pages

on:
  workflow_call:
    inputs:
      build-artifact-name:
        required: true
        type: string
        default: blog-build
      branch:
        required: false
        type: string
        default: main
      projectName:
        required: true
        type: string
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      PUSH_KEY:
        required: false
    outputs:
      url:
        description: "Deployed application url (by commit)"
        value: ${{ jobs.deploy-to-cloudflare-pages.outputs.url }}
      id:
        description: "Deployed application id (by commit)"
        value: ${{ jobs.deploy-to-cloudflare-pages.outputs.id }}


jobs:
  deploy-to-cloudflare-pages:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy-to-cloudflare-pages.outputs.url }}
      id: ${{ steps.deploy-to-cloudflare-pages.outputs.id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.build-artifact-name }}
          path: dist

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Deploy cloudFlare pages
        uses: cloudflare/pages-action@1
        id: deploy-to-cloudflare-pages
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 68cee62b3ea304dbae18339d0f4fe11e
          projectName: ${{ inputs.projectName }}
          branch: ${{ inputs.branch }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Send finished push
        run: curl --data "key=${{ secrets.PUSH_KEY }}&title=Yechanny%20Blog&msg=%EB%B8%94%EB%A1%9C%EA%B7%B8+%EC%BD%98%ED%85%90%EC%B8%A0%EA%B0%80+%EA%B2%8C%EC%8B%9C%EB%90%98%EC%97%88%EC%8A%B5%EB%8B%88%EB%8B%A4&event=Publish" --url https://api.simplepush.io/send