name: Trigger Publish

on:
  workflow_dispatch:
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Send started push
        run: curl -d "블로그 빌드가 시작되었습니다 ⚙️" ntfy.sh/yechanny-com

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

  build:
    needs: setup
    uses: ./.github/workflows/workflow-build.yml
    with:
      build_env: production
      app_env: production
      artifact-name: blog-build
    secrets:
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      BUILD_WEBHOOK_TOKEN: ${{ secrets.BUILD_WEBHOOK_TOKEN }}

  deploy-to-cloudflare-pages:
    needs: build
    uses: ./.github/workflows/workflow-deploy-to-cloudflare-pages.yml
    with:
      build-artifact-name: blog-build
      projectName: yechanny-com
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      PUSH_KEY: ${{ secrets.PUSH_KEY }}