name: Trigger Publish

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

  build:
    needs: setup
    uses: ./.github/workflows/workflow-build.yml
    with:
      build_env: production
      app_env: production
      artifact-name: blog-build

  deploy-to-cloudflare-pages:
    needs: build
    uses: ./.github/workflows/workflow-deploy-to-cloudflare-pages.yml
    with:
      build-artifact-name: blog-build
      projectName: yechanny-com
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}